version: "3.5"

services:
  backend:
    image: mynodeserver
    build: ./backend
    restart: always
    ports:
      - 3000:3000
    depends_on:
      - mysql
  mysql:
    image: node-database
    build: ./database
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: RootPassword
      MYSQL_DATABASE: study 
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    environment:
      ADMINER_DESIGN: dracula